# Type stub for xupy.  XuPy's own API is declared explicitly; the rest of the
# namespace is NumPy's (at runtime it is CuPy's on the GPU backend, with the
# same names), hence the star import.
from contextlib import AbstractContextManager
from types import ModuleType, TracebackType
from typing import Any

import numpy as _numpy
from numpy import *  # noqa: F401,F403
# `xupy.ma` follows the backend (numpy.ma on CPU, xupy.ma on GPU); statically it
# is typed as numpy.ma.
from numpy import ma as ma
from numpy.typing import DTypeLike

__version__: str
on_gpu: bool
has_multi_gpu: bool
n_gpus: int
np: ModuleType
npma: ModuleType

def use_cpu() -> None: ...
def use_gpu() -> None: ...
def backend(name: str) -> AbstractContextManager[ModuleType]: ...
def on_device(device_id: int) -> AbstractContextManager[None]: ...
def set_device(device_id: int) -> None: ...
def asnumpy(array: Any) -> Any: ...
def asmarray(array: Any) -> _numpy.ma.MaskedArray[Any, Any]: ...
def array_size(
    shape: int | tuple[int, ...] | list[tuple[int, ...]],
    dtype: DTypeLike = ...,
    out_unit: str = ...,
) -> int: ...

class NumpyContext:
    original_device: int | None
    def __init__(self) -> None: ...
    def __enter__(self) -> ModuleType: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

class MemoryContext:
    device_id: int | None
    auto_cleanup: bool
    force_cleanup: bool
    memory_threshold: float
    monitor_interval: float
    def __init__(
        self,
        device_id: int | None = None,
        auto_cleanup: bool = True,
        force_cleanup: bool = False,
        print_report: bool = True,
        memory_threshold: float = 0.9,
        monitor_interval: float = 1.0,
    ) -> None: ...
    def __enter__(self) -> MemoryContext: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def track_object(self, obj: Any) -> None: ...
    def clear_cache(self) -> None: ...
    def aggressive_cleanup(self) -> None: ...
    def emergency_cleanup(self) -> None: ...
    def get_memory_info(self) -> dict[str, Any]: ...
    def check_memory_pressure(self) -> bool: ...
    def auto_cleanup_if_needed(self) -> None: ...
    def monitor_memory(self, duration: float = 10.0) -> None: ...
    def force_memory_deallocation(self) -> None: ...
    def force_memory_pool_reset(self) -> None: ...
